### ISSUE TITLE
Not connecting !

### ISSUE THREAD

**Issue by Cosmic-Bug** [zeeoneofc/Alphabot-Md#43]
Connected ... {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
Koneksi Terputus...
Connected ... {
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Failure
        at WebSocket.<anonymous> (C:\Users\Desktop\Alphabot-Md\node_modules\@adiwajshing\baileys-md\lib\Socket\socket.js:442:13)
        at WebSocket.emit (node:events:390:28)
        at C:\Users\Desktop\Alphabot-Md\node_modules\@adiwajshing\baileys-md\lib\Socket\socket.js:229:35
        at Object.decodeFrame (C:\Users\Desktop\Alphabot-Md\node_modules\@adiwajshing\baileys-md\lib\Utils\noise-handler.js:143:17)
        at WebSocket.onMessageRecieved (C:\Users\Desktop\Alphabot-Md\node_modules\@adiwajshing\baileys-md\lib\Socket\socket.js:207:15)
        at WebSocket.emit (node:events:390:28)
        at Receiver.receiverOnMessage (C:\Users\Desktop\Alphabot-Md\node_modules\ws\lib\websocket.js:1098:20)
        at Receiver.emit (node:events:390:28)
        at Receiver.dataMessage (C:\Users\Desktop\Alphabot-Md\node_modules\ws\lib\receiver.js:513:14)
        at Receiver.getData (C:\Users\Desktop\Alphabot-Md\node_modules\ws\lib\receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-01-31T12:36:39.904Z
  }
}

**Comment by FatihArridho** [comment]
Hmm bisa kirim ss
